# Generated by Django 4.1.2 on 2022-10-24 13:52

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='accessory_id',
            field=models.IntegerField(default=builtins.id, verbose_name='ID комплектующего'),
        ),
    ]
