# Generated by Django 4.1.2 on 2022-10-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_accessory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='accessory_id',
            field=models.IntegerField(default=0, verbose_name='ID комплектующего'),
        ),
    ]
