# Generated by Django 4.1.2 on 2022-11-01 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_product_accessory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('JWT', models.CharField(blank=True, max_length=300, verbose_name='JWT')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role', verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='bucket',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser', verbose_name='ID Продукта'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
