# Generated by Django 4.1.3 on 2022-11-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser', verbose_name='ID пользователя'),
        ),
    ]
