# Generated by Django 4.1.2 on 2022-10-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Тип памяти')),
            ],
            options={
                'verbose_name': 'Тип памяти',
                'verbose_name_plural': 'Типы памяти',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Сокет')),
            ],
            options={
                'verbose_name': 'Сокет',
                'verbose_name_plural': 'Сокеты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(db_index=True, max_length=150, verbose_name='Производитель')),
                ('CPUmodel', models.CharField(db_index=True, max_length=150, verbose_name='Модель')),
                ('basefrequency', models.FloatField(verbose_name='Частота процессора')),
                ('RAMmax', models.IntegerField(verbose_name='Макcимальное количество RAM')),
                ('RAMcount', models.IntegerField(verbose_name='Количество каналов RAM')),
                ('TPD', models.IntegerField(verbose_name='TPD')),
                ('is_graphic', models.BooleanField(verbose_name='Есть графическое едро?')),
                ('RAMtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accessories.memorytypes', verbose_name='ID типа памяти')),
                ('socket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accessories.socket', verbose_name='ID Сокета')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
                'ordering': ['CPUmodel'],
            },
        ),
    ]
