# Generated by Django 4.1.2 on 2022-10-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='CoresCount',
            field=models.IntegerField(default=2, verbose_name='Количество ядер RAM'),
            preserve_default=False,
        ),
    ]
