# Generated by Django 4.1.2 on 2022-10-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0002_cpu_corescount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='CoresCount',
            field=models.IntegerField(verbose_name='Количество ядер'),
        ),
    ]
