# Generated by Django 4.1.2 on 2022-10-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0003_alter_cpu_corescount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Тип интерфейса подключения')),
            ],
            options={
                'verbose_name': 'Тип интерфейса подключения',
                'verbose_name_plural': 'Типы интерфейса подключения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VideoMemoryTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Тип памяти')),
            ],
            options={
                'verbose_name': 'Тип памяти',
                'verbose_name_plural': 'Типы памяти',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(db_index=True, max_length=150, verbose_name='Производитель')),
                ('GPUmodel', models.CharField(db_index=True, max_length=150, verbose_name='Модель')),
                ('amountvideomemory', models.FloatField(verbose_name='Количество видеопамяти')),
                ('buswidth', models.IntegerField(verbose_name='Разрядность шины')),
                ('connectiontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accessories.connectionstypes', verbose_name='Интерфейс подключения')),
                ('typememory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accessories.videomemorytypes', verbose_name='Тип памяти')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
                'ordering': ['GPUmodel'],
            },
        ),
    ]
