# Generated by Django 4.1.2 on 2022-10-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0004_connectionstypes_videomemorytypes_gpu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videomemorytypes',
            options={'ordering': ['title'], 'verbose_name': 'Тип видео памяти', 'verbose_name_plural': 'Типы видео памяти'},
        ),
    ]
