# Generated by Django 4.1.3 on 2022-12-03 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0007_remove_motherboard_typememory_id_motherboard_ramtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=150, verbose_name='Производитель')),
                ('RAMmodel', models.CharField(max_length=150, verbose_name='Модель')),
                ('countRAM', models.IntegerField(verbose_name='Количество памяти')),
                ('RAMtype', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Accessories.memorytypes', verbose_name='ID типа памяти')),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнские платы',
                'ordering': ['RAMmodel'],
            },
        ),
    ]
