# Generated by Django 4.1.3 on 2022-12-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0008_ram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ram',
            options={'ordering': ['RAMmodel'], 'verbose_name': 'Оперативная память', 'verbose_name_plural': 'Оперативные памяти'},
        ),
        migrations.AddField(
            model_name='ram',
            name='frequency',
            field=models.IntegerField(default=None, verbose_name='Частота'),
        ),
    ]
