# Generated by Django 4.1.3 on 2022-12-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0009_alter_ram_options_ram_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=150, verbose_name='Производитель')),
                ('MEMmodel', models.CharField(max_length=150, verbose_name='Модель')),
                ('countMEM', models.IntegerField(verbose_name='Количество памяти')),
                ('is_SSD', models.BooleanField(verbose_name='Have SSD?')),
            ],
            options={
                'verbose_name': 'Память',
                'verbose_name_plural': 'Памяти',
                'ordering': ['MEMmodel'],
            },
        ),
    ]
