# Generated by Django 4.1.3 on 2022-12-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0010_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='speedMEM',
            field=models.IntegerField(default=None, verbose_name='Скорость вращения шпинделя'),
        ),
    ]
