# Generated by Django 4.1.3 on 2022-12-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0012_ssdmemory_remove_memory_is_ssd'),
    ]

    operations = [
        migrations.CreateModel(
            name='PS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=150, verbose_name='Производитель')),
                ('PSmodel', models.CharField(max_length=150, verbose_name='Модель')),
                ('power', models.IntegerField(verbose_name='Количество памяти')),
            ],
            options={
                'verbose_name': 'Блок питания',
                'verbose_name_plural': 'Блоки питания',
                'ordering': ['PSmodel'],
            },
        ),
        migrations.AlterField(
            model_name='ssdmemory',
            name='speedMEMRead',
            field=models.IntegerField(default=None, verbose_name='Максимальная скорость последовательного чтения'),
        ),
        migrations.AlterField(
            model_name='ssdmemory',
            name='speedMEMWrite',
            field=models.IntegerField(default=None, verbose_name='Максимальная скорость последовательной записи'),
        ),
    ]
